if(CROSSGL_PYTHON3)
  get_property(CROSSGL_REQUIRED_PYTHON_TESTS DIRECTORY PROPERTY
    CROSSGL_REQUIRED_PYTHON_TESTS)
  get_property(CROSSGL_REGISTERED_TESTS DIRECTORY PROPERTY TESTS)
  set(CROSSGL_MISSING_PYTHON_TESTS)
  foreach(CROSSGL_REQUIRED_PYTHON_TEST IN LISTS CROSSGL_REQUIRED_PYTHON_TESTS)
    if(NOT "${CROSSGL_REQUIRED_PYTHON_TEST}" IN_LIST CROSSGL_REGISTERED_TESTS)
      list(APPEND CROSSGL_MISSING_PYTHON_TESTS
        "${CROSSGL_REQUIRED_PYTHON_TEST}")
    endif()
  endforeach()
  if(CROSSGL_MISSING_PYTHON_TESTS)
    string(REPLACE ";" ", " CROSSGL_MISSING_PYTHON_TESTS_TEXT
      "${CROSSGL_MISSING_PYTHON_TESTS}")
    message(FATAL_ERROR
      "Required Python-backed CrossGL tests were not registered: "
      "${CROSSGL_MISSING_PYTHON_TESTS_TEXT}")
  endif()
  list(LENGTH CROSSGL_REQUIRED_PYTHON_TESTS
    CROSSGL_REQUIRED_PYTHON_TEST_COUNT)
  message(STATUS
    "CrossGL required Python-backed tests registered: "
    "${CROSSGL_REQUIRED_PYTHON_TEST_COUNT}")
endif()
