"""Runtime package metadata helpers for CrossGL directory packages."""

from .loader import (
    LoaderArtifactPlan,
    RuntimeLoaderPlan,
    SourceFreeRuntimeArtifactHandoff,
    read_loader_plan,
    read_runtime_loader_plan_contract,
)
from .crosstl_adapters import (
    CrossTLAdapterDescriptor,
    CrossTLAdapterDiagnostic,
    CrossTLAdapterPackageReport,
    CrossTLRuntimeAdapterCandidate,
    CrossTLRuntimeAdapterLoadUnit,
    CrossTLRuntimeAdapterNormalizationReport,
    CrossTLRuntimeAdapterSkippedDescriptor,
    build_crosstl_runtime_adapter_load_units,
    build_crosstl_runtime_adapter_normalization_report,
    discover_crosstl_runtime_adapter_load_units,
    normalize_crosstl_runtime_adapter_candidates,
    read_crosstl_runtime_adapter_package,
    read_crosstl_runtime_adapter_load_units,
)
from .package_reader import (
    Artifact,
    CompatibilityDiagnostic,
    DebugMetadataRecord,
    PackageCompatibilityReport,
    PackageReadError,
    RuntimeArtifactSelection,
    RuntimePackage,
    TargetArtifactContract,
    read_compatibility_report,
    read_package,
    select_runtime_artifact,
)

__all__ = [
    "Artifact",
    "CompatibilityDiagnostic",
    "CrossTLAdapterDescriptor",
    "CrossTLAdapterDiagnostic",
    "CrossTLAdapterPackageReport",
    "CrossTLRuntimeAdapterCandidate",
    "CrossTLRuntimeAdapterLoadUnit",
    "CrossTLRuntimeAdapterNormalizationReport",
    "CrossTLRuntimeAdapterSkippedDescriptor",
    "DebugMetadataRecord",
    "LoaderArtifactPlan",
    "PackageCompatibilityReport",
    "PackageReadError",
    "RuntimeArtifactSelection",
    "RuntimeLoaderPlan",
    "RuntimePackage",
    "SourceFreeRuntimeArtifactHandoff",
    "TargetArtifactContract",
    "build_crosstl_runtime_adapter_load_units",
    "build_crosstl_runtime_adapter_normalization_report",
    "discover_crosstl_runtime_adapter_load_units",
    "read_compatibility_report",
    "normalize_crosstl_runtime_adapter_candidates",
    "read_crosstl_runtime_adapter_load_units",
    "read_crosstl_runtime_adapter_package",
    "read_loader_plan",
    "read_runtime_loader_plan_contract",
    "read_package",
    "select_runtime_artifact",
]
